DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS post;
CREATE TABLE profile(
profileID INT UNSIGNED AUTO_INCREMENT NOT NULL,
profileEmail VARCHAR(128)NOT NULL ,
	profilePhone VARCHAR(32),
	profileHash CHAR(128)NOT NULL,
	profileSalt CHAR(64)NOT NULL


)