DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS item;

CREATE TABLE item(
itemId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	itemName VARCHAR(128)NOT NULL,
	itemPrice VARCHAR(32)NOT NULL,
itemProfileId INT UNSIGNED NOT NULL
);

CREATE TABLE profile(
profileId INT UNSIGNED AUTO_INCREMENT NOT NULL,
profileEmail VARCHAR(128)NOT NULL ,
	profilePhone VARCHAR(32),
	profileHash CHAR(128)NOT NULL,
	profileSalt CHAR(64)NOT NULL


);
